NEW @W-16496381@ Implemented simple ConfigAction layer
forcedotcom/sfdx-scanner pull request #1572
Opened 2024-08-14 20:28 UTC by jfeingold35

2024-08-14 20:36 UTC, jfeingold35 commented on src/lib/actions/ConfigAction.ts
> -	configFactory: CodeAnalyzerConfigFactory;
Removed these dependencies because they don't do anything yet and the final fully-featured implementation might use something entirely different.

2024-08-14 20:36 UTC, jfeingold35 commented on src/lib/actions/ConfigAction.ts
> +		// TODO: Use the input to construct a more intelligent Config Model; possibly depend on a ConfigModelGenerator?
This is just the simplest possible implementation of the dummy config functionality. It will expand over time.

2024-08-14 20:36 UTC, jfeingold35 commented on messages/results-writer.md
Renaming this because the file it's associated with also got renamed.

2024-08-15 16:34 UTC, stephen-carter-at-sf requested changes
Let's emit a warning while we are in this state please.

2024-08-15 18:27 UTC, jfeingold35 commented on src/lib/writers/ConfigWriter.ts
> +			throw new Error(getMessage(BundleName.ConfigWriter, 'error.unrecognized-file-format', [file]));
We don't do the parent folder existence check for ResultsWriter either, so my preference would be that we log a bug and fix both in one swoop.

2024-08-15 18:46 UTC, stephen-carter-at-sf approved these changes

2024-08-15 18:59 UTC, merged