@W-10876586@ Changes to doc structure to parallelize 2.x and 3.x
forcedotcom/sfdx-scanner pull request #614
Opened 2022-03-28 16:40 UTC by rmohan20

Objectives:
* Keep version2 and 3 documentation in parallel
* Don't impact existing bookmarks

Changes made:
1. Renamed existing sidebar.yml to sidebar-v2, and created a new sidebar-v3 to hold the new changes
2. Created a parallel version for v3 as a separate path under docs/en
3. Modified sidebar.html to switch between version2 and version3. Version2 continues to be the existing link so that bookmarks are not broken.
4. `What's new in V3` page added to menu items
5. Changes to v3's index.md to point to `What's new in v3` page.
6. Placeholder page for upcoming engine information

2022-03-28 17:10 UTC, jfeingold35 commented on docs/_articles/en/v3.x/scanner-commands/add.md
> +See [Authoring Custom Rules](./en/custom-rules/author/) for more information.
Link to v3?

2022-03-28 17:28 UTC, rmohan20 commented on docs/_articles/en/v3.x/architecture/pmd-engine.md
> +[These steps](./en/faq/#questions-about-adding-and-removing-rules) outline how to enable PMD's built-in rules for other
good catch

2022-03-28 17:29 UTC, rmohan20 commented on docs/_articles/en/v3.x/architecture/retire-js-engine.md
> +For example, consider the following command, which will scan `MyProject` for vulnerable third-party libraries:
I don't think we plan to modify defaults at this time. But yeah, I haven't made any changes to this text at this point.

2022-03-28 17:34 UTC, rmohan20 commented on docs/_includes/sidebar.html
> +  <div class="language-picker">
This is the logic to switch between 2.x and 3.x documentation.

2022-03-28 17:34 UTC, rmohan20 commented on docs/_includes/sidebar.html
> +  {% assign sidebar = site.data.sidebar-v2 %}
This decides which sidebar structure should be used.

2022-03-28 17:35 UTC, rmohan20 commented on docs/_data/sidebar-v3.yml
> +- title:
Updated sidebar structure for 3.x

2022-03-28 17:35 UTC, rmohan20 commented on docs/_articles/en/v3.x/whats-new-v3.md
> +TODO: (Section on changes to existing engines)
Here's where the changes to eslint versions would be listed.

2022-03-28 17:38 UTC, ranekere-sfdc requested changes

2022-03-28 17:38 UTC, ranekere-sfdc commented on docs/_articles/en/v3.x/whats-new-v3.md
> +sfdx plugins:install @salesforce/sfdx-scanner@pilot
it might be sfdx-scanner@latest-pilot. need to check again

2022-03-28 17:38 UTC, ranekere-sfdc commented on docs/_articles/en/v3.x/scanner-commands/run.md
> + -v, --violations-cause-error
Yes, this flag was removed.

2022-03-28 21:04 UTC, ranekere-sfdc approved these changes

2022-03-28 22:57 UTC, merged

2022-03-29 17:16 UTC, rmohan20 commented on docs/_articles/en/v3.x/architecture/cpd-engine.md
> +`sfdx scanner:run --target "/some/path" --engine cpd`
@jfeingold35 Could you elaborate more on this?

2022-03-29 19:43 UTC, rmohan20 commented on docs/_articles/en/v3.x/custom-config/eslint.md
> +3. Ensure correctness of `.eslintrc.json`. Only JSON format of `.eslintrc` is supported today. However, there are no restrictions on the filename.
Eslint accepts `eslintrc` file in yaml format as well but we don't support it. Also, we want to tell users upfront that they are responsible to ensure correctness and we don't validate the contents for them. Will try rephrasing this.