v3.8.1 updates
forcedotcom/sfdx-scanner pull request #927
Opened 2022-12-22 17:07 UTC by teresa-allen-sfdc

- Jan 4 Release Summary
- new UnusedMethodsRule doc
- updating SFGE to Salesforce Graph Engine on Working with .... page

2022-12-27 23:42 UTC, rmohan20 commented on docs/_articles/en/v3.x/release-information.md
> +[Full Changelog](https://github.com/forcedotcom/sfdx-scanner/compare/v3.8.1...v3.6.2)
We should be using "3.7.1" instead of "3.6.2" in this diff.

2022-12-28 15:18 UTC, jfeingold35 requested changes

2022-12-28 15:18 UTC, jfeingold35 commented on docs/_articles/en/v3.x/salesforce-graph-engine/rules.md
> +- methods run through scanner:run, not scanner:run:dfa
This bullet point is incorrect. At present, the rule just detects unused private/protected constructors and private instance methods.
Also, the phrasing of line 76 seems to imply that such methods are inherently unused, which is incorrect. It's possible for them to be used, and we're just detecting when they aren't.

2022-12-28 15:18 UTC, jfeingold35 commented on docs/_articles/en/v3.x/salesforce-graph-engine/rules.md
> +To invoke UnusedMethodsRule, you must provide `--projectdir/-p` on `scanner:run`.
You also need to use `--engine sfge`.

2022-12-28 16:49 UTC, jfeingold35 commented on docs/_articles/en/v3.x/salesforce-graph-engine/rules.md
> +## UnusedMethodsRule
I missed this the first time around. The rule's name is actually "UnusedMethodRule", not "UnusedMethodsRule". That should be changed here and elsewhere.

2022-12-28 18:42 UTC, rmohan20 commented on docs/_articles/en/v3.x/salesforce-graph-engine/rules.md
> -#### See Also
I've moved this back to ApexCrudFlsViolationRule since the information isn't relevant to UnunsedMethodRule.

2022-12-28 18:43 UTC, jfeingold35 approved these changes

2022-12-28 18:44 UTC, merged